// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertXlsxToPDF(arg1) {
  return window['go']['main']['App']['ConvertXlsxToPDF'](arg1);
}

export function CountInvoices(arg1) {
  return window['go']['main']['App']['CountInvoices'](arg1);
}

export function DeleteInvoice(arg1) {
  return window['go']['main']['App']['DeleteInvoice'](arg1);
}

export function DeleteInvoiceTemplate(arg1) {
  return window['go']['main']['App']['DeleteInvoiceTemplate'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DownloadInvoiceFromGoogle(arg1) {
  return window['go']['main']['App']['DownloadInvoiceFromGoogle'](arg1);
}

export function ForceDownloadFromGoogle() {
  return window['go']['main']['App']['ForceDownloadFromGoogle']();
}

export function ForceUploadToGoogle() {
  return window['go']['main']['App']['ForceUploadToGoogle']();
}

export function GenerateInvoice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateInvoice'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAllClients() {
  return window['go']['main']['App']['GetAllClients']();
}

export function GetAllInvoiceTemplates() {
  return window['go']['main']['App']['GetAllInvoiceTemplates']();
}

export function GetAllInvoices() {
  return window['go']['main']['App']['GetAllInvoices']();
}

export function GetAllMyCompanies() {
  return window['go']['main']['App']['GetAllMyCompanies']();
}

export function GetAllProducts() {
  return window['go']['main']['App']['GetAllProducts']();
}

export function GetLastSyncTime(arg1) {
  return window['go']['main']['App']['GetLastSyncTime'](arg1);
}

export function GetMyCompanyInvoiceTemplates(arg1) {
  return window['go']['main']['App']['GetMyCompanyInvoiceTemplates'](arg1);
}

export function GetNextInvoiceNumber(arg1) {
  return window['go']['main']['App']['GetNextInvoiceNumber'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportProductsFromJSON(arg1) {
  return window['go']['main']['App']['ImportProductsFromJSON'](arg1);
}

export function RemoveMyCompanyInvoiceTemplate(arg1, arg2) {
  return window['go']['main']['App']['RemoveMyCompanyInvoiceTemplate'](arg1, arg2);
}

export function ResetProductsToFactory() {
  return window['go']['main']['App']['ResetProductsToFactory']();
}

export function SaveInvoiceFile(arg1, arg2) {
  return window['go']['main']['App']['SaveInvoiceFile'](arg1, arg2);
}

export function SearchClients(arg1) {
  return window['go']['main']['App']['SearchClients'](arg1);
}

export function SearchInvoices(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchInvoices'](arg1, arg2, arg3);
}

export function SearchProducts(arg1) {
  return window['go']['main']['App']['SearchProducts'](arg1);
}

export function SetMyCompanyInvoiceTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetMyCompanyInvoiceTemplate'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SyncAll() {
  return window['go']['main']['App']['SyncAll']();
}

export function UploadInvoiceToGoogleOnly(arg1) {
  return window['go']['main']['App']['UploadInvoiceToGoogleOnly'](arg1);
}

export function UpsertClient(arg1) {
  return window['go']['main']['App']['UpsertClient'](arg1);
}

export function UpsertCompany(arg1) {
  return window['go']['main']['App']['UpsertCompany'](arg1);
}

export function UpsertInvoice(arg1) {
  return window['go']['main']['App']['UpsertInvoice'](arg1);
}

export function UpsertInvoiceTemplate(arg1) {
  return window['go']['main']['App']['UpsertInvoiceTemplate'](arg1);
}

export function UpsertProduct(arg1) {
  return window['go']['main']['App']['UpsertProduct'](arg1);
}
