// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConvertXlsxToPDF(arg1:string):Promise<string>;

export function CountInvoices(arg1:string):Promise<number>;

export function DeleteInvoice(arg1:string):Promise<void>;

export function DeleteInvoiceTemplate(arg1:string):Promise<void>;

export function DeleteProduct(arg1:string):Promise<void>;

export function DownloadInvoiceFromGoogle(arg1:string):Promise<void>;

export function ForceDownloadFromGoogle():Promise<void>;

export function ForceUploadToGoogle():Promise<void>;

export function GenerateInvoice(arg1:models.Invoice,arg2:models.MyCompany,arg3:models.Client,arg4:string,arg5:boolean):Promise<string>;

export function GetAllClients():Promise<Array<models.Client>>;

export function GetAllInvoiceTemplates():Promise<Array<models.InvoiceTemplate>>;

export function GetAllInvoices():Promise<Array<models.Invoice>>;

export function GetAllMyCompanies():Promise<Array<models.MyCompany>>;

export function GetAllProducts():Promise<Array<models.Product>>;

export function GetLastSyncTime(arg1:string):Promise<string>;

export function GetMyCompanyInvoiceTemplates(arg1:string):Promise<Array<models.InvoiceTemplate>>;

export function GetNextInvoiceNumber(arg1:string):Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportProductsFromJSON(arg1:string):Promise<void>;

export function RemoveMyCompanyInvoiceTemplate(arg1:string,arg2:string):Promise<void>;

export function ResetProductsToFactory():Promise<void>;

export function SaveInvoiceFile(arg1:string,arg2:Array<number>):Promise<string>;

export function SearchClients(arg1:string):Promise<Array<models.Client>>;

export function SearchInvoices(arg1:string,arg2:number,arg3:number):Promise<Array<models.Invoice>>;

export function SearchProducts(arg1:string):Promise<Array<models.Product>>;

export function SetMyCompanyInvoiceTemplate(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SyncAll():Promise<Array<models.SyncResult>>;

export function UploadInvoiceToGoogleOnly(arg1:models.Invoice):Promise<void>;

export function UpsertClient(arg1:models.Client):Promise<void>;

export function UpsertCompany(arg1:models.MyCompany):Promise<void>;

export function UpsertInvoice(arg1:models.Invoice):Promise<void>;

export function UpsertInvoiceTemplate(arg1:models.InvoiceTemplate):Promise<void>;

export function UpsertProduct(arg1:models.Product):Promise<void>;
